# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/renesat/Project/MiniTicTacToe/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/renesat/Project/MiniTicTacToe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/renesat/Project/MiniTicTacToe/CMakeFiles /home/renesat/Project/MiniTicTacToe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/renesat/Project/MiniTicTacToe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

# target to build an object file
client/client.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/client.o
.PHONY : client/client.o

# target to preprocess a source file
client/client.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/client.i
.PHONY : client/client.i

# target to generate assembly for a file
client/client.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/client.s
.PHONY : client/client.s

# target to build an object file
client/mainClient.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/mainClient.o
.PHONY : client/mainClient.o

# target to preprocess a source file
client/mainClient.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/mainClient.i
.PHONY : client/mainClient.i

# target to generate assembly for a file
client/mainClient.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/mainClient.s
.PHONY : client/mainClient.s

# target to build an object file
server/server.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server/server.o
.PHONY : server/server.o

# target to preprocess a source file
server/server.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server/server.i
.PHONY : server/server.i

# target to generate assembly for a file
server/server.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server/server.s
.PHONY : server/server.s

# target to build an object file
tictactoe/tictactoe.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tictactoe/tictactoe.o
.PHONY : tictactoe/tictactoe.o

# target to preprocess a source file
tictactoe/tictactoe.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tictactoe/tictactoe.i
.PHONY : tictactoe/tictactoe.i

# target to generate assembly for a file
tictactoe/tictactoe.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tictactoe/tictactoe.s
.PHONY : tictactoe/tictactoe.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... client/client.o"
	@echo "... client/client.i"
	@echo "... client/client.s"
	@echo "... client/mainClient.o"
	@echo "... client/mainClient.i"
	@echo "... client/mainClient.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
	@echo "... tictactoe/tictactoe.o"
	@echo "... tictactoe/tictactoe.i"
	@echo "... tictactoe/tictactoe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

